#!/bin/sh
set -e
if [ "$1" = purge ]
then
	rm -rf /var/spool/cron/atjobs /var/spool/cron/atspool
fi

# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		if [ "$1" = "purge" ]; then
			export _DEB_SYSTEMD_HELPER_PURGE=1
		else
			# To explicitly clean the environment.
			export _DEB_SYSTEMD_HELPER_PURGE=0
		fi
		deb-systemd-helper disable atd.service >/dev/null
	fi
fi
# End automatically added section

