#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/gator-daemon" ] || [ -e "/etc/init/gator-daemon.conf" ]; then
	if [ ! -e "/etc/init/gator-daemon.conf" ]; then
		update-rc.d gator-daemon defaults >/dev/null
	fi
	invoke-rc.d gator-daemon start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f gator-daemon remove >/dev/null || exit $?
# End automatically added section
