#!/bin/sh

set -e
if ! getent group | grep -q libuuid; then
groupadd -f -K GID_MIN=1 -K GID_MAX=999 libuuid
fi
if ! getent passwd | grep -q libuuid; then
   useradd -d /var/lib/libuuid -K UID_MIN=1 -K UID_MAX=499 -g libuuid libuuid
fi
[ -f /etc/subuid ] && sed -i "/^libuuid:/d" /etc/subuid
[ -f /etc/subgid ] && sed -i "/^libuuid:/d" /etc/subgid
chown libuuid:libuuid /usr/sbin/uuidd
chmod 6755 /usr/sbin/uuidd



exit 0
